#!/usr/bin/env python3
"""Produce a conservative source-level character package inventory.

This is an audit aid, not a completeness or gameplay verifier. Presence of files
never proves they are referenced, compatible, licensed, or functional.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

GAME = Path(sys.argv[1]).resolve()
OUT = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else Path("character-package-audit.md")
BASIC = GAME / "lua/class/basic.lua"
if not BASIC.is_file():
    raise SystemExit(f"Missing expected roster source: {BASIC}")

source = BASIC.read_text(encoding="utf-8", errors="replace")
match = re.search(r"ns\.CharactersLayout\s*=\s*\{([\s\S]*?)\n\}", source)
if not match:
    raise SystemExit("Could not locate ns.CharactersLayout in basic.lua")
body = re.sub(r"--\[\[[\s\S]*?\]\]", "", match.group(1))
body = re.sub(r"--[^\n]*", "", body)
names = []
for item in re.finditer(r"'([^']*)'|\"([^\"]*)\"|(?<![\w])_None(?![\w])", body):
    name = item.group(1) or item.group(2) or ""
    if name and name.lower() != "none" and name not in names:
        names.append(name)

all_files = [p for p in GAME.rglob("*") if p.is_file()]
relative = [(p, p.relative_to(GAME).as_posix()) for p in all_files]
text_files = []
for path, rel in relative:
    if path.suffix.lower() in {".lua", ".cpp", ".h", ".hpp", ".xml", ".plist", ".json", ".ini"}:
        try:
            text_files.append((rel, path.read_text(encoding="utf-8", errors="replace")))
        except OSError:
            pass

def under_dir(rel: str, parent: str, name: str) -> bool:
    parts = rel.lower().split("/")
    try:
        idx = parts.index(parent.lower())
    except ValueError:
        return False
    return idx + 1 < len(parts) and parts[idx + 1] == name.lower()

def fmt(value):
    return str(value).replace("|", "\\|").replace("\n", " ")

rows = []
for name in names:
    low = name.lower()
    header = any(rel.lower() == f"classes/core/shinobi/{low}.hpp" for _, rel in relative)
    # This candidate stores fighter sprites/config under Resources/Unit/<name>/.
    unit = []
    for _, rel in relative:
        parts = rel.lower().split("/")
        if "unit" in parts and low in parts[parts.index("unit") + 1:]:
            unit.append(rel)
    audio = [rel for _, rel in relative if under_dir(rel, "Audio", name)]
    named_selection = [rel for _, rel in relative if Path(rel).name.lower() in {
        f"{low}_select.png", f"{low}_half.png", f"{low}_font.png"
    }]
    ai_refs = [rel for rel, content in text_files if "setAIHandler" in content and re.search(rf"HeroEnum::{re.escape(name)}\b", content, re.IGNORECASE)]
    # Atlas-packed selection art may not exist as standalone PNG files.
    atlas = GAME / "Resources/Select.plist"
    atlas_text = atlas.read_text(encoding="utf-8", errors="replace") if atlas.is_file() else ""
    required_frames = [f"{name}_select.png", f"{name}_half.png", f"{name}_font.png"]
    frames_found = [frame for frame in required_frames if frame.lower() in atlas_text.lower()]
    if len(frames_found) == len(required_frames) or len(named_selection) == 3:
        selection = "ALL_3_FRAMES_FOUND"
    elif frames_found or named_selection:
        selection = "PARTIAL_FRAMES_FOUND"
    else:
        selection = "NOT_FOUND_MANUAL_CHECK"
    rows.append((name, "YES" if header else "NO/MONOLITHIC", "ENUM_REFERENCE_FOUND" if enum_refs else "NO_ENUM_REFERENCE_FOUND", "SKILL_ATLAS_FOUND" if skill_atlas else "NO_SKILL_ATLAS_FOUND", len(unit), len(audio), selection, "AI_REGISTRATION_REFERENCE_FOUND" if ai_refs else "MANUAL_AI_AUDIT_REQUIRED"))

OUT.parent.mkdir(parents=True, exist_ok=True)
with OUT.open("w", encoding="utf-8") as f:
    f.write("# Automated Character Package Inventory\n\n")
    f.write(f"- Candidate root: `{GAME}`\n")
    f.write(f"- Roster source: `lua/class/basic.lua`\n")
    f.write(f"- Unique selectable names found: **{len(names)}**\n")
    f.write("- Generated by `scripts/audit_character_packages.py`.\n")
    f.write("- **Warning:** this is a filename/source-reference inventory only. It does not prove a character is complete, licensed, selectable at runtime, or playable by AI. Manual skill-view, animation, audio-trigger, combat, and device tests remain mandatory.\n\n")
    f.write("| Character | Separate C++ header | Native enum reference | Skill atlas file | Unit/resource file matches | Exact-name audio files | Selection art check | AI registration clue |\n")
    f.write("|---|---|---|---|---:|---:|---|---|\n")
    for row in rows:
        f.write("| " + " | ".join(fmt(x) for x in row) + " |\n")
    f.write("\n## Interpretation rules\n\n")
    f.write("- A `NO/MONOLITHIC` header result means the code may be in a shared C++ file; it is not proof the character is absent. Unit/resource counts are broad filename matches and do not prove the correct frames load.\n")
    f.write("- Zero audio/unit files or no named AI registration requires manual investigation; shared assets and indirect registrations can create false negatives.\n")
    f.write("- A selection art result is based on finding expected frame names in `Select.plist` or standalone files; runtime selection still needs testing.\n")
    f.write("- Do not promote any entry to implemented or verified based on this report alone. Record voice lines, SFX triggers, skills, resource paths, AI behavior, provenance, and rights separately.\n")
print(f"Wrote {OUT}; audited {len(names)} unique selectable names.")
