#!/usr/bin/env python3
"""Produce a conservative source-level character package inventory.

This is an audit aid, not a completeness or gameplay verifier. Presence of files
never proves they are referenced, compatible, licensed, or functional.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

GAME = Path(sys.argv[1]).resolve()
OUT = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else Path("character-package-audit.md")
BASIC = GAME / "lua/class/basic.lua"
if not BASIC.is_file():
    raise SystemExit(f"Missing expected roster source: {BASIC}")

source = BASIC.read_text(encoding="utf-8", errors="replace")
match = re.search(r"ns\.CharactersLayout\s*=\s*\{([\s\S]*?)\n\}", source)
if not match:
    raise SystemExit("Could not locate ns.CharactersLayout in basic.lua")
body = re.sub(r"--\[\[[\s\S]*?\]\]", "", match.group(1))
body = re.sub(r"--[^\n]*", "", body)
names = []
for item in re.finditer(r"'([^']*)'|\"([^\"]*)\"|(?<![\w])_None(?![\w])", body):
    name = item.group(1) or item.group(2) or ""
    if name and name.lower() != "none" and name not in names:
        names.append(name)

all_files = [p for p in GAME.rglob("*") if p.is_file()]
relative = [(p, p.relative_to(GAME).as_posix()) for p in all_files]
text_files = []
for path, rel in relative:
    if path.suffix.lower() in {".lua", ".cpp", ".h", ".hpp", ".xml", ".plist", ".json", ".ini"}:
        try:
            text_files.append((rel, path.read_text(encoding="utf-8", errors="replace")))
        except OSError:
            pass

def under_dir(rel: str, parent: str, name: str) -> bool:
    parts = rel.lower().split("/")
    try:
        idx = parts.index(parent.lower())
    except ValueError:
        return False
    return idx + 1 < len(parts) and parts[idx + 1] == name.lower()

def fmt(value):
    return str(value).replace("|", "\\|").replace("\n", " ")

rows = []
for name in names:
    low = name.lower()
    header = any(rel.lower() == f"classes/core/shinobi/{low}.hpp" for _, rel in relative)
    char_lua = [rel for rel, _ in text_files if rel.lower().endswith(".lua") and low in Path(rel).stem.lower()]
    element = [rel for _, rel in relative if under_dir(rel, "Element", name)]
    audio = [rel for _, rel in relative if under_dir(rel, "Audio", name)]
    named_selection = [rel for _, rel in relative if Path(rel).name.lower() in {
        f"{low}_select.png", f"{low}_half.png", f"{low}_font.png"
    }]
    ai_refs = [rel for rel, content in text_files if re.search(rf"\bAI_{re.escape(name)}\b", content, re.IGNORECASE)]
    # Atlas-packed selection art may not exist as standalone PNG files.
    selection = "STANDALONE_FILES_FOUND" if named_selection else "ATLAS_OR_MISSING_NEEDS_MANUAL_CHECK"
    rows.append((name, "YES" if header else "NO/MONOLITHIC", len(char_lua), len(element), len(audio), selection, "POSSIBLE_AI_REFERENCE" if ai_refs else "NO_NAMED_AI_HOOK_FOUND"))

OUT.parent.mkdir(parents=True, exist_ok=True)
with OUT.open("w", encoding="utf-8") as f:
    f.write("# Automated Character Package Inventory\n\n")
    f.write(f"- Candidate root: `{GAME}`\n")
    f.write(f"- Roster source: `lua/class/basic.lua`\n")
    f.write(f"- Unique selectable names found: **{len(names)}**\n")
    f.write("- Generated by `scripts/audit_character_packages.py`.\n")
    f.write("- **Warning:** this is a filename/source-reference inventory only. It does not prove a character is complete, licensed, selectable at runtime, or playable by AI. Manual skill-view, animation, audio-trigger, combat, and device tests remain mandatory.\n\n")
    f.write("| Character | Separate C++ header | Character-named Lua files | Element files | Exact-name audio files | Selection art check | AI hook check |\n")
    f.write("|---|---:|---:|---:|---:|---|---|\n")
    for row in rows:
        f.write("| " + " | ".join(fmt(x) for x in row) + " |\n")
    f.write("\n## Interpretation rules\n\n")
    f.write("- A `NO/MONOLITHIC` header result means the code may be in a shared C++ file; it is not proof the character is absent.\n")
    f.write("- Zero audio/element files or no named AI hook requires manual investigation; shared assets and indirect registrations can create false negatives.\n")
    f.write("- A selection art result without standalone files may mean the image is packed in an atlas; inspect `Select.plist` and runtime selection.\n")
    f.write("- Do not promote any entry to implemented or verified based on this report alone. Record voice lines, SFX triggers, skills, resource paths, AI behavior, provenance, and rights separately.\n")
print(f"Wrote {OUT}; audited {len(names)} unique selectable names.")
